<?php

use \LiquidoBrl\PayInPhpSdk\Util\Brazil\PaymentMethod;
use \LiquidoBrl\PayInPhpSdk\Util\PayInStatus; ?>

<div>
    <h1>Liquido Pagamentos</h1>
    <?php if (!$this->hasFailed()): ?>
        <h3>Número do pedido:
            <?php echo $this->getOrderId() ?>
        </h3>

        <?php if (
            $this->getPaymentMethodType() == PaymentMethod::BOLETO
            && $this->getTransferStatus() != PayInStatus::SETTLED
        ): ?>
            <h2>Pague seu boleto pelo seu app de pagamentos ou Internet Banking</h2>
            <!-- <div id="pdf-container"></div> -->
            <img id="barcode-image" alt="Barcode Image">
            <a target="_blank" href="<?php echo $this->getBoletoUrl() ?>">Baixar Boleto</a>
            <hr />
            <div id="boleto-digital-line-copy-paste">
                <fieldset class="fieldset">
                    <label for="boleto-digital-line">Se preferir, você pode pagá-lo copiando e colando o código
                        abaixo:</label><br>
                    <input type="text" id="boleto-digital-line" name="boleto-digital-line" readonly
                        value="<?php echo $this->getBoletoDigitalLine() ?>"><br>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button onclick="copyToClipboard('boleto-digital-line')" class="action primary"
                            title="<?php echo __('Copiar código') ?>">
                            <span>
                                <?php echo __('Copiar código') ?>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
        <?php elseif ($this->getTransferStatus() == PayInStatus::IN_PROGRESS): ?>
            <h3><strong>Você já gerou um pagamento com
                    <?php echo __($this->getPaymentMethodName()) ?>
                </strong></h3>
        <?php elseif ($this->getTransferStatus() == PayInStatus::SETTLED): ?>
            <h3><strong>Você já pagou com
                    <?php echo __($this->getPaymentMethodName()) ?>
                </strong></h3>
        <?php endif; ?>

    <?php else: ?>
        <a href="/checkout/liquidobrl/index">Alterar método de pagamento</a>
    <?php endif; ?>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsbarcode/3.11.5/JsBarcode.all.min.js"></script>
<script>
    require(
        ['jquery', 'jquery/ui'],
        function ($) {

            function createBarcode(type = "ITF", barcode = '', options = {}) {
                try {
                    JsBarcode('#barcode-image', barcode, {
                        format: type,
                        ...options,
                    });
                } catch (err) {
                    console.error(err);
                }
            }

            $(document).ready(function () {
                createBarcode("ITF", "<?= $this->getBoletoBarCode(); ?>");
            });

        }
    );
</script>