<?php

use \LiquidoBrl\PayInPhpSdk\Util\Common\PaymentMethod;
use \LiquidoBrl\PayInPhpSdk\Util\PayInStatus; ?>

<div>
    <h1>Liquido Pagamentos</h1>
    <?php if (!$this->hasFailed()) : ?>
        <h3>Número do pedido: <?php echo $this->getOrderId() ?></h3>
        <?php if (
            $this->getPaymentMethodType() == PaymentMethod::CREDIT_CARD
            && $this->getTransferStatus() != PayInStatus::SETTLED
        ) : ?>
            <h3>Você pagou: <?php echo $this->getHowCustomerPaid(); ?></h3>
            <h3>Valor total: R$ <?php echo $this->getOrderTotal(); ?></h3>
        <?php elseif ($this->getTransferStatus() == PayInStatus::IN_PROGRESS) : ?>
            <h3><strong>Você já gerou um pagamento com <?php echo __($this->getPaymentMethodName()) ?></strong></h3>
        <?php elseif ($this->getTransferStatus() == PayInStatus::SETTLED) : ?>
            <h3><strong>Você já pagou com <?php echo __($this->getPaymentMethodName()) ?></strong></h3>
        <?php endif; ?>
    <?php else : ?>
        <a href="/checkout/liquidobrl/index">Alterar método de pagamento</a>
    <?php endif; ?>
</div>