<?php

use \LiquidoBrl\PayInPhpSdk\Util\Common\PaymentMethod;
use \LiquidoBrl\PayInPhpSdk\Util\PayInStatus;

$successfulResult = true;
$resultCssClass = "success";
$resultHeaderInfoImage = $this->getViewFileUrl("Liquido_PayIn::images/common/success-result.png");
$resultHeaderInfoDescription = $this->getSuccessMessage();
$instructions = $this->getInstructions();
$establishments = $this->getEStablishments();

if ($this->hasFailed()) {
    $successfulResult = false;
    $resultCssClass = "failed";
    $resultHeaderInfoImage = $this->getViewFileUrl("Liquido_PayIn::images/common/error-icon-2.png");
    $resultHeaderInfoDescription = $this->getErrorMessage();
}

?>

<div class="result-container">

    <div class="result-header <?php echo $resultCssClass; ?>">
        <h1>Liquido Pagos</h1>
        <h3>Pago en efectivo</h3>
        <div class="result-header-info">
            <img src="<?php echo $resultHeaderInfoImage ?>" alt="Result Info Image">
            <h3>
                <?php echo $resultHeaderInfoDescription; ?>
            </h3>
        </div>
    </div>

    <div id="result-main-content">

        <?php if (!$this->hasFailed()): ?>

            <div class="result-content">

                <?php if (
                    $this->getPaymentMethodType() == PaymentMethod::CASH
                    && $this->getTransferStatus() != PayInStatus::SETTLED
                ): ?>

                    <div class="result-card">
                        <header>
                            <h3><strong>Referencia para pago:</strong></h3>
                            <h2>
                                <?php echo $this->getCashCode() ?>
                            </h2>
                        </header>
                        <h3>
                            Número de pedido:
                            <strong>
                                <?php echo $this->getOrderId() ?>
                            </strong>
                        </h3>
                        <h4>Acércate con la referencia de pago a uno de nuestros establecimientos aliados para realizar el pago
                        </h4>
                    </div>
                    <?php if ($instructions['country'] == 'CO'): ?>
                        <div class="result-instructions">
                            <small>* Establecimientos aliados: <?php echo $instructions['establishments'] ?></small>
                            <small>
                                <?php echo $instructions['efecty'] ?> <strong> <?php echo $instructions['convenio'] ?> </strong>
                            </small>
                        </div>
                    <?php elseif ($instructions['country'] == 'MX'): ?>
                        <div class="result-instructions">
                            <label for="establishments">Establecimientos aliados:</label>
                            <select name="establishments" id="establishments">
                                <option value="">Seleccionar::</option>
                                <?php foreach ($establishments as $establishment): ?>
                                    <option value="<?php echo $establishment[1] ?>"><?php echo $establishment[0] ?></option>
                                <?php endforeach; ?>
                            </select>

                            <div id="show198" class="myDiv" style="display: none;">
                                <small>* Convênio: <strong>198</strong> </small>
                            </div>     
                            <div id="show3724" class="myDiv" style="display: none;">
                                <small>* Convênio: <strong>3724</strong> </small>
                            </div>     
                            <div id="show7292" class="myDiv" style="display: none;">
                                <small>* Convênio: <strong>7292</strong> </small>
                            </div>     
                            <div id="show7755" class="myDiv" style="display: none;">
                                <small>* Convênio: <strong>7755</strong> </small>
                            </div>     
                            <div id="show1420712" class="myDiv" style="display: none;">
                                <small>* Convênio: <strong>1420712</strong> </small>
                            </div>                        
                        </div>
                    <?php endif; ?>
                <?php elseif ($this->getTransferStatus() == PayInStatus::IN_PROGRESS): ?>
                    <div class="result-warning">
                        <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/warning-icon.png") ?>"
                            alt="Warning Image">
                        <h3><strong>Ya has generado un pago con
                                <?php echo $this->getPaymentMethodName() ?>!
                            </strong></h3>
                    </div>
                <?php elseif ($this->getTransferStatus() == PayInStatus::SETTLED): ?>
                    <div class="result-warning">
                        <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/warning-icon.png") ?>"
                            alt="Warning Image">
                        <h3>
                            <strong>
                                Ya pagaste con
                                <?php echo $this->getPaymentMethodName() ?>!
                            </strong>
                        </h3>
                    </div>
                <?php endif; ?>

            </div>

            <div>
                <?php
                echo $this->getLayout()
                    ->createBlock("Magento\Framework\View\Element\Template")
                    // ->createBlock("Liquido\PayIn\Block\Common\LiquidoOrderSummary")
                    ->setTemplate("Liquido_PayIn::common/liquido-order-summary.phtml")->toHtml()
                    ?>
            </div>

        <?php else: ?>
            <div class="back-button-container">
                <a class="action submit primary" href="/checkout/liquidoco/index">Cambiar método de pago</a>
            </div>
        <?php endif; ?>

    </div>
</div>