<?php
    /*echo'<pre>';
    print_r($this->getDetailsByCountry());
    echo'</pre>';

    echo'<pre>';
    print_r($this->getCardInstallmentsTextsForOptions());
    echo'</pre>';

    echo'<pre>';
    print_r($this->getProposalDetails());
    echo'</pre>';*/
?>

<div class="liquido-container">

    <div class="header-content">
        <h1>
            <?php echo __('Liquido Pagamentos') ?>
        </h1>
        <?php
        $payin_method_name = $this->getCardPayInMethodName();
        ?>
        <h3>
            <?php echo __('Pagar com ') ?>
            <?php echo __($payin_method_name) ?>
        </h3>
        <div class="images-row">
            <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/mastercard.png"); ?>"
                alt="Master Card Image">
            <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/visa.png"); ?>" alt="Visa Image">
            <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/americanexpress.png"); ?>"
                alt="AExpress Image">
            <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/dinersclub.png"); ?>"
                alt="Diners Club Image">
        </div>
    </div>

    <div id="main-content">

        <form id="credit-card-customer-form" data-mage-init='{"validation": {}}' class="form"
            action="<?php echo $this->getUrl('checkout/liquido/creditcard', ['_secure' => true]); ?>" method="post">
            <fieldset class="fieldset">

                <h2>
                    <?php echo __('Dados do cartão') ?>
                </h2>
                <!-- <div>
                <table>
                    <tr>
                        <td>
                            <input type="radio" id="vi" name="flag" value="VI">
                            <label for="vi" class="label"><span></span></label>
                        </td>
                        <td>
                            <input type="radio" id="mc" name="flag" value="MC">
                            <label for="mc" class="label"><span></span></label>
                        </td>
                        <td>
                            <input type="radio" id="ae" name="flag" value="AE">
                            <label for="ae" class="label"><span></span></label>
                        </td>
                        <td>
                            <input type="radio" id="jcb" name="flag" value="JCB">
                            <label for="jcb" class="label"><span></span></label>
                        </td>
                        <td>
                            <input type="radio" id="di" name="flag" value="DI">
                            <label for="di" class="label"><span></span></label>
                        </td>
                        <td>
                            <input type="radio" id="dn" name="flag" value="DN">
                            <label for="dn" class="label"><span></span></label>
                        </td>
                        <td>
                            <input type="radio" id="elo" name="flag" value="ELO">
                            <label for="elo" class="label"><span></span></label>
                        </td>
                    </tr>
                </table>
            </div> -->
                <div class="field required">
                    <div class="control">
                        <div>
                            <input type="number" name="card-number" id="card-number" value=""
                                title="<?php echo __('Número') ?>" class=""
                                data-validate="{required:true, 'validate-cc-number':true}">
                        </div>
                    </div>
                    <label for="card-number" class="label"><span>
                            <?php echo __('Número do cartão') ?>
                        </span></label>
                </div>
                <div class="field required">
                    <div class="control">
                        <div>
                            <input type="text" name="card-name" id="card-name" value=""
                                title="<?php echo __('Nome do titular') ?>" data-validate="{required:true}">
                        </div>
                    </div>
                    <label for="card-name" class="label">
                        <span>
                            <?php echo __('Nome do titular') ?>
                        </span>
                    </label>
                </div>
                <div class="form-row">
                    <div class="field required">
                        <div class="control">
                            <div>
                                <input type="text" name="card-expire-date" id="card-expire-date" placeholder="MM/YY"
                                    value="" title="<?php echo __('Mês / Ano') ?>"
                                    class="minimum-length-4 maximum-length-5"
                                    data-validate="{required:true, 'validate-length':true}">
                            </div>
                        </div>  
                        <label for="card-expire-date" class="label">
                            <span>
                                <?php echo __('Mês / Ano') ?>
                            </span>
                        </label>
                    </div>
                    <div class="field required">
                        <div class="control">
                            <div>
                                <input type="number" name="card-cvv" id="card-cvv" value="" title="<?php echo __('CVV') ?>"
                                    class="minimum-length-3 maximum-length-4"
                                    data-validate="{required:true, 'validate-digits':true, 'validate-length':true}">
                            </div>
                        </div>
                        <label for="card-cvv" class="label"><span>
                                <?php echo __('CVV') ?>
                            </span></label>
                    </div>
                </div>
                <div class="form-row">
                    <?php if ($this->getCountry() == 'CO' || $this->getCountry() == 'MX'): ?>
                            <div class="field required">
                                <div class="control">
                                    <select name="customer-doc-type" id="customer-doc-type">
                                        <option value="CC">CC</option>
                                        <option value="CE">CE</option>
                                        <option value="NIT">NIT</option>
                                    </select>
                                </div>
                                <label for="customer-doc-type" class="label"><span>Tipo de documento</span></label>
                            </div>
                            <div class="field required">
                                <div class="control">
                                    <div>
                                        <input type="text" name="customer-doc" id="customer-doc" value=""
                                            title="<?php echo __('CC') ?>" class="input-text"
                                            data-validate="{'required-entry':true}">
                                    </div>
                                </div>
                                <label for="customer-doc" class="label"><span>Número del documento</span></label>
                            </div>
                    <?php elseif ($this->getCountry() == 'BR'): ?>
                            <div class="field required">
                                <div class="control">
                                    <input type="text" name="customer-doc" id="customer-doc" value=""
                                        title="<?php echo __('CPF') ?>" class="input-text"
                                        data-validate="{'required-entry':true, 'validate-cpf':true}">
                                </div>
                                <label for="customer-doc" class="label"><span>
                                        <?php echo __('CPF') ?>
                                    </span></label>
                            </div>
                    <?php endif ?>
                </div>
                <div class="field required">
                    <div class="control">
                        <select name="card-installments" id="card-installments">
                            <?php
                            $optionsInfoArray = $this->getCardInstallmentsTextsForOptions();
                            ?>
                            <?php foreach ($optionsInfoArray as $index => $optionInfo): ?>
                                    <option value="<?php echo $index + 1 ?>"><?php echo $optionInfo; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <label for="card-installments" class="label"><span>
                            <?php echo __('Número de parcelas') ?>
                        </span></label>
                </div>
            </fieldset>
            <!-- <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" id="credit-card-submit-button" class="action submit primary"
                        title="<?php // echo __('Pagar') ?>"><span>
                            <?php // echo __('Pagar') ?>
                        </span></button>
                </div>
            </div> -->
        </form>

        <div>
            <?php
            echo $this->getLayout()
                ->createBlock("Magento\Framework\View\Element\Template")
                // ->createBlock("Liquido\PayIn\Block\Common\LiquidoOrderSummary")
                ->setTemplate("Liquido_PayIn::common/liquido-order-summary.phtml")->toHtml()
                ?>
            <div class="action-bar">
                <button type="submit" form="credit-card-customer-form" class="pay-button">Pagar</button>
            </div>
        </div>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'jquery/ui',
            'Liquido_PayIn/js/lib/jquery.maskedinput.min'
        ],
        function (jQuery) {
            jQuery("#card-expire-date").mask("99/99");
            jQuery("#customer-cpf").mask("999.999.999-99");             /*jQuery(document).ready(function() {                 jQuery('input[type=radio][name=flag]').change(function() {                     jQuery('#flag-checked').val(this.value);                 });
             });*/

        }
    );
</script>