<div class="liquido-container">

    <div class="header-content">
        <h1>Liquido Pagos</h1>
        <h2>
            <?php echo $this->getPsePayInMethodName(); ?>
        </h2>
        <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/col/pse.png"); ?>" alt="PSE Image">
    </div>

    <div id="main-content">

        <form id="pse-customer-form" data-mage-init='{"validation": {}}' class="form" method="POST"
            action="<?php echo $this->getUrl('checkout/liquidoco/pse', ['_secure' => true]); ?>">
            <fieldset class="fieldset">

                <h2>Datos Personales</h2>

                <div class="form-row">

                    <div class="field required" id="field-phone">
                        <div class="control">
                            <div class="same-row">
                                <input type="text" name="customer-ddi-number" id="customer-ddi-number" value="+57"
                                    title="Teléfono" class="input-text" data-validate="{'required-entry':true}"
                                    disabled>
                                <div>
                                    <input type="text" name="customer-phone-number" id="customer-phone-number" value=""
                                        title="Teléfono" class="input-text"
                                        data-validate="{'required-entry':true, 'validate-number':true}">
                                </div>
                            </div>
                        </div>
                        <label for="customer-phone-number" class="label"><span>Número de teléfono</span></label>
                    </div>

                    <div class="field required">
                        <div class="control">
                            <select name="customer-person-type" id="customer-person-type">
                                <option value="NATURAL">Natural</option>
                                <option value="LEGAL">Legal</option>
                            </select>
                        </div>
                        <label for="customer-person-type" class="label"><span>Tipo de persona</span></label>
                    </div>
                </div>

                <div class="form-row">
                    <div class="field required">
                        <div class="control">
                            <select name="customer-doc-type" id="customer-doc-type">
                                <option value="CC">CC</option>
                                <option value="CE">CE</option>
                                <option value="NIT">NIT</option>
                            </select>
                        </div>
                        <label for="customer-doc-type" class="label"><span>Tipo de documento</span></label>
                    </div>

                    <div class="field required">
                        <div class="control">
                            <div>
                                <input type="text" name="customer-doc-number" id="customer-doc-number" value=""
                                    title="Número del Documento" class="input-text"
                                    data-validate="{'required-entry':true}">
                            </div>
                        </div>
                        <label for="customer-doc-number" class="label">Número de documento</span></label>
                    </div>
                </div>

                <div class="field required">
                    <div class="control">
                        <select name="customer-financial-institution" id="customer-financial-institution">
                            <?php
                            $financialInstitutions = $this->getPseFinancialInstitutionsList();
                            ?>
                            <?php foreach ($financialInstitutions as $institution): ?>
                                <option value="<?php echo $institution->financial_institution_code ?>">
                                    <?php echo $institution->financial_institution_code ?> - <?php echo $institution->financial_institution_name ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <label for="customer-financial-institution" class="label"><span>
                            <?php echo __('Institución financiera') ?>
                        </span></label>
                </div>
            </fieldset>
            <!-- <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Enviar"><span>Enviar</span></button>
                </div>
            </div> -->
        </form>

        <div>
            <?php
            echo $this->getLayout()
                ->createBlock("Magento\Framework\View\Element\Template")
                // ->createBlock("Liquido\PayIn\Block\Common\LiquidoOrderSummary")
                ->setTemplate("Liquido_PayIn::common/liquido-order-summary.phtml")->toHtml()
                ?>
            <div class="action-bar">
                <button type="submit" form="pse-customer-form" class="pay-button">Ir al banco</button>
            </div>
        </div>
    </div>
</div>