<div class="liquido-container">

    <div class="header-content">
        <h1>Liquido Pagos</h1>
        <h2>Elige tu método de pago</h2>
    </div>

    <?php
    use \Liquido\PayIn\Util\Common\LiquidoPayInMethod;

    $colombia_payin_methods = $this->getLiquidoColombiaPayInMethods();
    ?>

    <div id="main-content">
        <ul id="payin-methods">
            <?php foreach ($colombia_payin_methods as $payin_method): ?>
                <?php if ($payin_method == LiquidoPayInMethod::CREDIT_CARD): ?>
                    <a class="payin-method-link-co" href="<?php echo $this->getUrl('checkout/liquido/creditcardform') ?>">
                    <?php else: ?>
                        <a class="payin-method-link-co"
                            href="<?php echo $this->getPayInMethodViewRoute($payin_method["title"]) ?>">
                        <?php endif ?>
                        <li>
                            <img src="<?php echo $this->getViewFileUrl($payin_method["image"]); ?>"
                                alt="PayIn method image">
                            <div class="payin-method-single">
                                <p>
                                    <?php echo __($payin_method["title"]); ?>
                                </p>
                                <small>
                                    <?php echo __($payin_method["description"]); ?>
                                </small>
                            </div>
                        </li>
                    </a>
                <?php endforeach; ?>
        </ul>
        <div class="order-summary">
            <table>
                <thead>
                    <h2>Resumen de pedido</h2>
                </thead>
                <tbody>
                    <tr>
                        <td>Subtotal</td>
                        <td>.....................</td>
                        <td>$100</td>
                    </tr>
                    <tr>
                        <td>Descuento</td>
                        <td>.....................</td>
                        <td>$10</td>
                    </tr>
                    <tr>
                        <td>Envio</td>
                        <td>.....................</td>
                        <td>$110</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr id="total">
                        <td>Total</td>
                        <td></td>
                        <td>$22</td>
                    </tr>
                </tfoot>
            </table>
            <!-- <a>Continuar</a> -->

            <div class="action-bar">
                <button id="go-on-button">Continuar</button>
            </div>
        </div>
    </div>
</div>
<script>

</script>