<?php

use \LiquidoBrl\PayInPhpSdk\Util\Colombia\PaymentMethod;
use \LiquidoBrl\PayInPhpSdk\Util\PayInStatus;

?>

<div class="result-container">

    <div class="result-header">
        <h1>Liquido Pagos</h1>
        <h2>Pago en efectivo</h2>
        <div class="result-header-info">
            <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/success-result.png"); ?>"
                alt="Result Image">
            <h3>Referencia de pago generada con êxito</h3>
        </div>
    </div>

    <div id="result-main-content">

        <div class="result-content">

            <div class="result-card">
                <header>
                    <h3>Referencia para pago:</h3>
                    <h2>
                        <?php echo $this->getCashCode() ?>
                    </h2>
                </header>
                <hr>
                <h3>Número de pedido:
                    <?php echo $this->getOrderId() ?>
                </h3>
                <h4>Acércate con la referencia de pago a uno de nuestros establecimientos aliados para realizar el pago
                </h4>
            </div>
            <div class="result-instructions">
                <small>*Establecimientos aliados:...</small>
                <small>*Para pagos en establecimientos Efecty presentar el número de convenio: XXXXXXXXX</small>
            </div>
            <?php if (!$this->hasFailed()): ?>
                <!-- <h3>Número de pedido:
                            <?php // echo $this->getOrderId() ?>
                        </h3> -->

                <?php if (
                    $this->getPaymentMethodType() == PaymentMethod::CASH
                    && $this->getTransferStatus() != PayInStatus::SETTLED
                ): ?>
                    <h3>Por favor copie el código y diríjase a uno de nuestro establecimientos aliados para realizar el pago.
                    </h3>
                    <small style="color: #6E716E">
                        * Establecimientos aliados: Baloto, Banco de Bogotá, Bancolombia, Brinks, Davivienda, Efecty,
                        Superpagos,
                        Sured.
                    </small>
                    <br />
                    <small style="color: #6E716E">
                        * Para pagos en redes Efecty se debe presentar el número de convenio <strong>112766</strong>.
                    </small>
                    <hr />
                    <div id="cash-code-copy-paste">
                        <fieldset class="fieldset">
                            <label for="cash-code">Código Cash: </label><br>
                            <input type="text" id="cash-code" name="cash-code" readonly
                                value="<?php echo $this->getCashCode() ?>"><br>
                        </fieldset>
                        <!-- <div class="actions-toolbar">
                                                                                                                                            <div class="primary">
                                                                                                                                                <button onclick="copyToClipboard('cash-code')" class="action primary" title="Copie el código">
                                                                                                                                                    <span>Copie el código</span>
                                                                                                                                                </button>
                                                                                                                                            </div>
                                                                                                                                        </div> -->
                    </div>
                <?php elseif ($this->getTransferStatus() == PayInStatus::IN_PROGRESS): ?>
                    <h3><strong>Ya has generado un pago con
                            <?php echo $this->getPaymentMethodName() ?>
                        </strong></h3>
                <?php elseif ($this->getTransferStatus() == PayInStatus::SETTLED): ?>
                    <h3><strong>Ya pagaste con
                            <?php echo $this->getPaymentMethodName() ?>
                        </strong></h3>
                <?php endif; ?>
            <?php else: ?>
                <a href="/checkout/liquidoco/index">Cambiar método de pago</a>
            <?php endif; ?>
        </div>

        <div>
            <?php
            echo $this->getLayout()
                ->createBlock("Magento\Framework\View\Element\Template")
                // ->createBlock("Liquido\PayIn\Block\Common\LiquidoOrderSummary")
                ->setTemplate("Liquido_PayIn::common/liquido-order-summary.phtml")->toHtml()
                ?>
        </div>
    </div>
</div>