<?php

use \LiquidoBrl\PayInPhpSdk\Util\Colombia\PaymentMethod;
use \LiquidoBrl\PayInPhpSdk\Util\PayInStatus;

$successfulResult = true;
$resultCssClass = "success";
$resultHeaderInfoImage = $this->getViewFileUrl("Liquido_PayIn::images/common/success-result.png");
$resultHeaderInfoDescription = $this->getSuccessMessage();

if ($this->hasFailed()) {
    $successfulResult = false;
    $resultCssClass = "failed";
    $resultHeaderInfoImage = $this->getViewFileUrl("Liquido_PayIn::images/common/error-icon-2.png");
    $resultHeaderInfoDescription = $this->getErrorMessage();
}

?>

<div class="result-container">

    <div class="result-header <?php echo $resultCssClass; ?>">
        <h1>Liquido Pagos</h1>
        <h3>Transferencia bancaria</h3>
        <div class="result-header-info">
            <img src="<?php echo $resultHeaderInfoImage ?>" alt="Result Info Image">
            <h3>
                <?php echo $resultHeaderInfoDescription; ?>
            </h3>
        </div>
    </div>

    <div id="result-main-content">

        <?php if (!$this->hasFailed()): ?>

            <div class="result-content">

                <?php if (
                    $this->getPaymentMethodType() == PaymentMethod::PSE
                    && $this->getTransferStatus() != PayInStatus::SETTLED
                ): ?>

                    <div class="result-card">

                        <header>
                            <?php if (!empty($this->getPseLink())): ?>
                                <h3>Clique en el siguiente link para realizar el pago</h3>
                                <div id="pse-link">
                                    <fieldset class="fieldset">
                                        <h2>
                                            <!-- <label for="pse-link">Link PSE: </label> -->
                                            <a id="pse-link" name="pse-link" href="<?php echo $this->getPseLink() ?>"
                                                target="_blank">Paga
                                                haciendo
                                                clic
                                                aquí.</a>
                                        </h2>
                                    </fieldset>
                                </div>
                            <?php else: ?>
                                <h3>Tu pagaste:
                                    <?php echo $this->getOrderTotal() ?>
                                </h3>
                            <?php endif ?>
                        </header>

                        <h3>
                            Numéro del pedido:
                            <strong>
                                <?php echo $this->getOrderId() ?>
                            </strong>
                        </h3>
                    </div>
                <?php elseif ($this->getTransferStatus() == PayInStatus::IN_PROGRESS): ?>
                    <div class="result-warning">
                        <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/warning-icon.png") ?>"
                            alt="Warning Image">
                        <h3><strong>Ya has generado un pago con
                                <?php echo $this->getPaymentMethodName() ?>
                            </strong></h3>
                    </div>
                <?php elseif ($this->getTransferStatus() == PayInStatus::SETTLED): ?>
                    <div class="result-warning">
                        <img src="<?php echo $this->getViewFileUrl("Liquido_PayIn::images/common/warning-icon.png") ?>"
                            alt="Warning Image">
                        <h3><strong>Ya pagaste con
                                <?php echo $this->getPaymentMethodName() ?>
                            </strong></h3>
                    </div>
                <?php endif; ?>

            </div>

            <div>
                <?php
                echo $this->getLayout()
                    ->createBlock("Magento\Framework\View\Element\Template")
                    // ->createBlock("Liquido\PayIn\Block\Common\LiquidoOrderSummary")
                    ->setTemplate("Liquido_PayIn::common/liquido-order-summary.phtml")->toHtml()
                    ?>
            </div>

        <?php else: ?>
            <div class="back-button-container">
                <a class="action submit primary" href="/checkout/liquidoco/index">Cambiar método de pago</a>
            </div>
        <?php endif; ?>

    </div>
</div>